### ISSUE TITLE
NoSuchMethodError: net.minecraft.client.Minecraft.getMinecraft()

### ISSUE THREAD

**Issue by mmelvin0** [OmegaJak/Power_Drop#1]
I'm getting this crash with 1.1.1 of your mod:

https://git.io/vxLUW

Do you perhaps mistakenly upload a dev build to Curse?

**Comment by ACGaming** [comment]
Can confirm this!

**Comment by OmegaJak** [comment]
Thanks for letting me know, something must have gone wrong when when building the file for 1.1.1. This issue should be fixed with the 1.1.2 file. Please let me know if it's not!
